// Copyright (C) 1991-2016 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus Prime Version 16.0 (Build Build 211 04/27/2016)
// Created on Wed Nov 09 00:08:02 2016

Ordenador Ordenador_inst
(
	.I0(I0_sig) ,	// input  I0_sig
	.I1(I1_sig) ,	// input  I1_sig
	.I2(I2_sig) ,	// input  I2_sig
	.I3(I3_sig) ,	// input  I3_sig
	.S0(S0_sig) ,	// output  S0_sig
	.S1(S1_sig) ,	// output  S1_sig
	.S2(S2_sig) ,	// output  S2_sig
	.S3(S3_sig) 	// output  S3_sig
);

